config/routes.rb
Rails.application.routes.draw do

  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

    #get 'sessions/create'
    
    #get 'sessions/destroy'
    
    get 'home/show'

    get '/bikes/:id/switchAvailability', to: 'bikes#switchAvailability'
    get '/bikes/new', to: 'bikes#new'
    get '/bikes/:id/edit', to: 'bikes#edit'
    get '/bikes/:id/checkin', to: 'bikes#checkin'
    
    get '/about', to: 'home#about'
    get '/pricing', to: 'home#pricing'
    get '/error', to: 'home#error'
    
    #Creates standard routes for different controllers
    resources :bikes
    resources :renters
    resources :tickets
    
    #Makes home page bikes#index view
    #root :to => redirect('/bikes')
    

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    
    # Added these for cucumber testing
    # sessions#create_guest makes a fake user for Cucumber testing with hard coded data 
    # so that session[:logged_in] is true
    get 'auth/guest', to: 'sessions#create_guest'
    # sessions#loggedin checks that the user is logged in and outputs session[:logged_in] to log folder
    # Since it is used by Cucumber, the output is put into the bottom of log/test.log
    get 'auth/loggedin', to: 'sessions#loggedin'

    resources :sessions, only: [:create, :destroy]
    get '/login', to: 'sessions#login'
    
    resource :home, only: [:show]

    root to: "home#show"
    
    resources :payments, only: [:index, :new, :create]
    
    get '*path' => redirect('/error')
    
    
end

app/models/renter.rb
#Validates and stores renter information and credentials
#Model for reading google+ info
class Renter < ActiveRecord::Base
  self.primary_key = :renterID
  has_many :tickets
  has_many :bikes, :through => :tickets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
    # Sets checks for when data is entered into the database
    # :presence specifies that the field cannot be empty
    # :numericality specifies that the input can only be a number 
    validates :renterID, :presence => true, :format => {:with => /\d{21}/, :message => "must contain 21 numbers"}
    validates :renterName, :presence => true, :format => {:with => /\w*/, :message => "can only include letters"}
    validates :email, :presence => true, :format => {:with => /.*@.*\.[coe][ord][mgu]/, :message => "requires input like example@gmail.com or example@tulane.edu"}
    # validates :phone, :presence => false, :format => {:with => /\(\d{3}\)-\d{3}-\d{4}/, :message => "requires a phone number like (123)-456-7890"}
    # validates :cCN, :presence => false, :format => {:with => /\d{16}/, :message => "must contain 16 numbers"}
  
  #Allows us to read in google+ information
  def self.from_omniauth(auth)
    where(provider: auth.provider, renterID: auth.uid).first_or_create do |renter|
      renter.provider = auth.provider
      renter.renterID = auth.uid
      renter.renterName ||= auth.info.name
      renter.oauth_token = auth.credentials.token
      renter.oauth_expires_at = Time.at(auth.credentials.expires_at)
      renter.picture = auth.info.image
      #Adds in dummy values for other required info
      renter.email = auth.info.email
      renter.admin = false
      # renter.phone = "(234)-394-1948"
      # renter.cCN = "1234567890123456"
      renter.save!
    end 
  end
end

app/controllers/renters_controller.rb
#The default controller for the Renter Model
class RentersController < ApplicationController
    
    before_action :force_log_in
    before_action :require_admin, except: [:show,:edit,:update]
    
    #Shows a list of the renters currently in the database (10 at a time) (CRUD Method)
    def index
        @renters = Renter.page(params[:page]).per(10)
    end
    
    #Shows info about the renter
    def show
        if !(current_user.id==params[:id] || current_user.admin)
            flash[:warning] = "You don't have permission to see this."
            redirect_to "/"
        end
        @renter = Renter.find(params[:id])
        if session[:logged_in]
           if Ticket.exists?(renterID: session[:renter_id])
               @tickets = Ticket.where(renterID: session[:renter_id]).order(checkout: :desc).reorder(active: :desc)
               @tickets = Kaminari.paginate_array(@tickets).page(params[:ticket_page]).per(3)
            else
                @tickets = nil
           end
        end
    end
    
    #Creates a spot for a new renter in the Renter Model
    def new
        @renter = Renter.new
    end
    
    #Creates and populates renter information into a new renter (CRUD Method)
    def create
        renter_params[:admin] = false;
        @renter = Renter.new(renter_params)
        if @renter.valid?
            @renter.save
            flash[:create] = "#{@renter.renterName} has been added!"
            redirect_to :action => "show", :id => @renter.id
        else
            flash[:errors] = @renter.errors
            redirect_to :action => "new"
        end
    end
    
    #Finds the renter to edit based on the Renter ID
    def edit
        @renter = Renter.find params[:id]
    end
    
    #Updates the renter with the information stored in renter_params (CRUD Method)
    def update
        @renter = Renter.find params[:id]
        if @renter.update(renter_params)
            flash[:update] = "#{@renter.renterName} has been updated!"
            redirect_to :action => "show", :id => @renter.id
        else
            flash[:errors] = @renter.errors
            redirect_to :action => "edit"
        end
    end
    
    #Destroys the renter (CRUD Method)
    def destroy
        @renter = Renter.find params[:id]
        @renter.destroy
        flash[:delete] = "#{@renter.renterName} has been deleted!"
        redirect_to renters_path
    end
    
    private
    #Used for CRUD
    #requires renterID, provider, renterName, oauth_token, oauth_expires_at, cCN, tickets, numRents, birthday
        def renter_params
            params.require(:renter).permit(:renterID, :provider, :renterName, :oauth_token, :oauth_expires_at, :cCN, :tickets, :numRents, :birthday)
        end
end

app/helpers/renters_helper.rb
#Empty
module RentersHelper
end

app/views/renters/_renter_form.html.erb
  
<!--<section class="formElem">-->
<!--    <%= f.label :renterID, 'Identification Number' %>-->
<!--    <%= f.text_field :renterID %>-->
<!--</section>-->

<section class="formElem">
    <%= f.label :renterName, 'Firstname Lastname' %>
    <%= f.text_field :renterName, maxlength: 32 %>
</section>

<!--<section class="formElem">-->
<!--    %= f.label :provider, 'Provider' %>-->
<!--    %= f.text_field :provider %>-->
<!--</section>-->

<!--<section class="formElem">-->
<!--    %= f.label :cCN, 'Credit Card Number' %>-->
<!--    %= f.text_field :cCN %>-->
<!--</section>-->

<section class="formElem">
    <%= f.label :birthday, 'Date of Birth' %>
    <%= f.date_select :birthday %>
</section>

<section class="formElem">
    <%= f.label :email, 'Email Address' %>
    <%= f.text_field :email, maxlength: 32 %>
</section>

<section class="formElem">
    <%= f.label :phone, 'Phone Number (with area code)' %>
    <%= f.text_field :phone, maxlength: 12 %>
</section>

app/views/renters/_renter_nav.html.erb
<nav class="uk-text-center">
	
	<!--Show add/edit if on index/show respectively-->
	<% if current_page?("/renters") %>
		<%= link_to 'Add new renter', new_renter_path, class: "uk-button uk-button-default" %>
	<% elsif params[:action] == "show" %>
		<%= link_to 'Update info', edit_renter_path(@renter), class: "uk-button uk-button-default" %>
	<% end %>
	
</nav>

app/views/renters/_renter_show.html.erb
<h1 class="stretch-none uk-text-center"><%= @renter.renterName.split(" ")[0] %>'s Page</h1>

<%= render :partial => '/renters/renter_nav' %>
    
<section class="uk-text-center">
	
	<!--Show user's profile picture if set-->
	<% if @renter.picture %>
		<img src="<%= @renter.picture %>" alt="Profile picture for <%= @renter.renterName %>" width='200' class="uk-border-circle uk-margin-top">
	<% end %>
	
	<!--Show user's contact information-->
	<p>Email: <%= @renter.email %></p>
	<p>Phone: <%= @renter.phone %></p>
	<!--<p>Credit Card: % if @renter.cCN %>************%= @renter.cCN[@renter.cCN.length-4..@renter.cCN.length] %> % end %></p>-->
	
	<!--Show logout option, only if user is on user's own page-->
	<% if current_user.id==params[:id] %>
  
    <%= link_to "Log out", signout_path, id: "sign_out", class: "uk-button uk-button-primary" %>
                    
	<% end %>
	
</section>

app/views/renters/_renter_tickets.html.erb
<% if session[:logged_in] and tickets != nil%>

<h2 style="text-align: center">Your Tickets</h2>
<div class="uk-margin-bottom">
    <div class="dataDisp uk-margin-bottom">
		
		<% tickets.each do |t| %>
		    <div class="uk-card uk-card-hover dataBlock uk-padding uk-text-uppercase">
			    <div class="uk-card-body uk-grid-collpase uk-child-width-2-1 uk-text-center" uk-grid>
			        <a href="<%= bikes_path %>/<%= Bike.find_by(bikeid: t.bikeid).id %>" class="dataContent">

						<!--Bike Image-->
						<div class="uk-card-media-left dataPicMargin">
				            <% curr_bike = Bike.find_by(bikeid: t.bikeid) %>
				            <h3>Bike Info</h3>
							<img class="uk-border-rounded dataPic" style="background-image: url('<%= curr_bike.picture %>');" alt="<%= curr_bike.color %> <%= curr_bike.style %> Bike" src="<%= curr_bike.picture %>">
						</div>
					</a>
						
					<!--Bike Status-->
					<div class="status uk-border-rounded
					<% if t.active %>
						available
					<% else %>
						unavailable
					<% end %>"></div>
					
					<a href="<%= tickets_path %>/<%= t.id %>" class="dataContent">
						<!--Bike Content-->
					    <h3>Ticket Info</h3>
			
					    <p>Checked out:  <%= t.checkout.strftime("%m/%d/%Y") %></p>
					    <% if t.checkin %>
					        <p>Checked in: <%= t.checkin.strftime("%m/%d/%Y") %></p>
						    <p> Total
				    	<% else %>
					    	<p> Current
				    	<% end %>
				    	 fare: $<%= number_with_precision(t.totalFare, :precision => 2) %></p>
			    	 </a>
				    <% if t.active %>
				        <a href="/bikes/<%= t.bikeid %>/switchAvailability" class="uk-button uk-default-button">Check In</a>
				    <% end %>
			    </div>
		    </div>
		<% end %>
	</div>
    <div style="text-align: center;">
    	<%= paginate @tickets, :param_name => "ticket_page" %>
    	<div style="clear: both;">
    		<%= page_entries_info @tickets %>
    	</div> 
    </div>
</div>
<%end%>

app/views/renters/edit.html.erb
<% @pageName = "Renters" %>
<% @pageSection = "Edit" %>

<%= render :partial => 'renter_nav' %>

<h2>Edit a User</h2>

<%= form_for @renter do |f| %>

  <%= render :partial => 'renter_form', :locals => {:f => f} %>
  
  <section class="formElem" id="submitSect">
    <%= button_to "Update Renter", renter_path(@renter), :method => :create, :class => "boot", :id => "create" %>
    <%= link_to "Delete Renter", renter_path(@renter), :method => :delete, :class => "boot", :id => "delete", :data => { confirm: "Are you sure you want to delete Renter #{@renter.renterName}?" } %>
  </section>

<% end %>

app/views/renters/index.html.erb
<% @pageName = "Renters" %>
<% @pageSection = "All" %>

<%= render :partial => 'renter_nav' %>

<h2>Users</h2>
<!--Displays table listing attributes for all bikes -->
<table>
	
	<!--Creates a row that is then populated with the headers (titles) for each of the columns-->
	<tr>
		<th>Name</th>
	</tr>
	
	<!--Creates a row that is populated with the data of the current user into each column-->
	<% @renters.each do |t| %>
		 <tr>
			<td>
				<!--Generates a link to the renter's page according to the renter's path and id-->
				<a href="<%= renters_path %>/<%= t.id %>"><%= t.renterName %></a>
			</td>
		</tr>
	<% end %>
	
</table>

<!-- Adds pagination/navigation from Kaminari -->
<div style="text-align: center;">
	<%= paginate @renters %>
	<div style="clear: both;">
		<%= page_entries_info @renters %>
	</div>
</div>

app/views/renters/new.html.erb
<% @pageName = "Renters" %>
<% @pageSection = "New" %>

<%= render :partial => 'renter_nav' %>

<h2>Add a User</h2>

<%= simple_form_for @renter do |f| %>

  <%= render :partial => 'renter_form', :locals => {:f => f} %>
  
  <section class="formElem">
    <%= f.button "Add User", :type => "submit" %>
  </section>

<% end %>

app/views/renters/show.html.erb
<% @pageName = "#{@renter.renterName.split(" ")[0]}" %>
<% @pageSection = "Profile" %>

<% if session[:logged_in] %>
    <%= render :partial => '/renters/renter_show' %>
<% else %>
    <%= render :partial => 'login_section' %>
<% end %>

<% if current_user.id==params[:id] %>
		<%= render :partial => '/renters/renter_tickets', :locals => {:tickets => @tickets} %>
<% end %>