config/routes.rb
Rails.application.routes.draw do

  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

    #get 'sessions/create'
    
    #get 'sessions/destroy'
    
    get 'home/show'

    get '/bikes/:id/switchAvailability', to: 'bikes#switchAvailability'
    get '/bikes/new', to: 'bikes#new'
    get '/bikes/:id/edit', to: 'bikes#edit'
    get '/bikes/:id/checkin', to: 'bikes#checkin'
    
    get '/about', to: 'home#about'
    get '/pricing', to: 'home#pricing'
    get '/error', to: 'home#error'
    
    #Creates standard routes for different controllers
    resources :bikes
    resources :renters
    resources :tickets
    
    #Makes home page bikes#index view
    #root :to => redirect('/bikes')
    

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    
    # Added these for cucumber testing
    # sessions#create_guest makes a fake user for Cucumber testing with hard coded data 
    # so that session[:logged_in] is true
    get 'auth/guest', to: 'sessions#create_guest'
    # sessions#loggedin checks that the user is logged in and outputs session[:logged_in] to log folder
    # Since it is used by Cucumber, the output is put into the bottom of log/test.log
    get 'auth/loggedin', to: 'sessions#loggedin'

    resources :sessions, only: [:create, :destroy]
    get '/login', to: 'sessions#login'
    
    resource :home, only: [:show]

    root to: "home#show"
    
    resources :payments, only: [:index, :new, :create]
    
    get '*path' => redirect('/error')
    
    
end

app/models/bike.rb
#Validates bike instance variables before storage
class Bike < ActiveRecord::Base
    self.primary_key = :bikeid
    has_many :tickets
    has_many :renters, :through => :ticket
    # Sets checks for when data is entered into the database
    # :presence specifies that the field cannot be empty
    # :numericality specifies that the input can only be a number 
    validates :bikeid, :presence => true, :format => {:with => /\w\d\d\d\d/, :message => "the format has to be similar to A0000"}
    validates :serialnumber, :presence => true, :numericality => {:only_integer => false, :message => "must be a number"}
    validates :condition, :presence => true, :format => {:with => /\w*/, :message => "the condition field can only include letters"}
    validates :style, :presence => true
    validates :size, :presence => true, :numericality => {:only_integer => false, :message => "must be a number"}
    validates :color, :presence => true, :format => {:with => /\w*/, :message => "the color field can only include letters"}
    #validates :availability, :presence => true
    validates :location, :presence => true
    validates :fare, :presence => true, :numericality => {:only_integer => false, :message => "must be a number"}
    validates :picture, :presence => true
    
end

app/controllers/bikes_controller.rb
#The default controller for the Bike Model
class BikesController < ApplicationController
    before_action :force_log_in, :except => [:index, :show]
    before_action :checkCCN, :only => [:checkin]
    
    #Used to get tickets for logged in user (if the user is logged in) and to 
    #get all the available bikes
    def index 
        if session[:logged_in]
            if Ticket.exists?(renterID: session[:renter_id])
                @tickets = Ticket.where(renterID: session[:renter_id]).order(checkout: :desc).reorder(active: :desc)
                # Converts the @tickets array into a paginate_array using Kaminari
                # Necessary because Kaminari doesn't work with normal arrays
                @tickets = Kaminari.paginate_array(@tickets).page(params[:ticket_page]).per(3)
            else
                # Kaminari expects to use page on the Model itself (thats the only way it works)
                # It can have an order inbetween (example below in else)
                @tickets = nil
            end
        end
        #@bikes = Bike.all
        # Decides how many bikes to show per page
        @bikes = Bike.order("availability desc").page(params[:bike_page]).per(9)
    end
    
    #Shows the bikes based on bike :id
    def show
        @bike = Bike.find(params[:id])
    end
    
    #Finds current bike and flips the availability and creates the ticket
    #for the user if the bike was available. 
    #If the bike was unavailable
    #then it checks the bike in and closes the ticket
    def switchAvailability
        #Flips the availability
        @bike = Bike.find(params[:id])
        #flash[:newAvailability] = @bike.availability
        @newAvailability = !@bike.availability
        
        #Stores hash for updating/creating new ticket upon check in/out
        attributes = Hash.new

        if @bike.availability #Checks bike out
            #Creates new ticket from the given data
            #attributes[:ticket] = 'TN123'
            attributes[:renterID] = current_user.renterID
            attributes[:renterName] = session[:renter_name]
            attributes[:email] = current_user.email
            attributes[:bikeid] = @bike.bikeid
            #attributes[:cCN] = current_user.cCN
            attributes[:serialnumber] = @bike.serialnumber
            attributes[:checkout] = DateTime.now
            #attributes[:checkin] = null
            attributes[:location] = @bike.location
            attributes[:fare] = @bike.fare
            attributes[:active] = true
            @ticket = Ticket.new(attributes)
            @ticket.save!
            
            #Updates availability and pushes flash message
            flash[:success] = "Bike sucessfully checked out!"
            @bike.update_attribute(:availability, @newAvailability)
            
            redirect_to :controller => 'tickets', :action => 'show', :id => @ticket.id
        else #Checkin bike
        #Checkin the bike and updates ticket to complete
            # session[:checkin] = DateTime.now
            # session[:active] = false
            @ticket = Ticket.find_by(renterID: current_user.renterID, bikeid: @bike.bikeid, active: true)
            if @ticket
                #Updates ticket values if found
                session[:amount] = @ticket.totalFare
                session[:bikeid] = @bike.bikeid
                # @ticket.update(attributes)
                # flash[:success] = "Bike successfully checked in!"
                # @bike.update_attribute(:availability, @newAvailability)
                redirect_to :controller => 'payments', :action => 'new'
            else
                #Returns warning if you are trying to check in a bike you did not check out
                flash[:warning] = "You did not check out this bike!"
                if @ticket
                    redirect_to :controller => 'tickets', :action => 'show', :id => @ticket.id
                else
                    redirect_to bikes_path
                end
            end
            
            
        end

    end
    
    #Update current bike's checkin time to current time and active status to false
    def checkin
        attributes = Hash.new
        @bike = Bike.find(params[:id])
        @newAvailability = !@bike.availability
        attributes[:checkin] = DateTime.now
        attributes[:active] = false
        @bike.update_attribute(:availability, @newAvailability)
        @ticket = Ticket.find_by(renterID: current_user.renterID, bikeid: @bike.bikeid, active: true)
        @ticket.update(attributes)
        flash[:success] = "Bike successfully checked in!"
        session[:amount] = nil
        session[:bikeid] = nil
        session[:paid] = nil
        redirect_to :controller => 'tickets', :action => 'show', :id => @ticket.id
    end

    #Used for the default REST "new" action
    def new
        @bike = Bike.new
    end
    
    #Used for the CRUD "create" action
    def create
        @bike = Bike.new(bike_params)
        # Checks the validations in bike.rb to make sure all necessary fields 
        # are filled
        if @bike.valid?
            @bike.save
            #Notify creation of bike
            flash[:create] = "#{@bike.bikeid} has been added!"
            #Redirect to the newly created bike page
            redirect_to :action => "show", :id => @bike.id
        else
            #Notify errors of bike creation
            flash[:errors] = @bike.errors
            #Redirect back to the same page, with errors now shown on top
            redirect_to :action => "new"
        end
    end
    
    #Used for the default REST "edit" action
    def edit
        @bike = Bike.find params[:id]
    end
    
    #Used for the CRUD "update" action
    def update
        @bike = Bike.find params[:id]
        if @bike.update(bike_params)
            #Notify update of bike
            flash[:update] = "#{@bike.bikeid} has been updated!"
            #Redirect to the newly created bike page
            redirect_to :action => "show", :id => @bike.id
        else
            flash[:errors] = @bike.errors
            redirect_to :action => "edit"
        end
    end
    
    #Used for the CRUD "destroy" action
    def destroy
       @bike = Bike.find(params[:id])
       @bike.destroy
       flash[:delete] = "#{@bike.bikeid} has been deleted!"
       redirect_to bikes_path
    end
    
    private
        #Contains all parameters for when a bike is made
        #[bikeid, serialnumber, rating, condition, maintenance, style, size, color, availability, lastcheck, location, fare, accessories, picture]
        def bike_params
            params.require(:bike).permit(:bikeid, :serialnumber, :rating, :condition, :maintenance, :style, :size, :color, :availability, :lastcheck, :location, :fare, :accessories, :picture)
        end
    
end

app/helpers/bikes_helper.rb
#Empty
module BikesHelper
end

app/views/bikes/_bike_form.html.erb
<section class="formElem">
  <%= f.label :bikeid, 'Identification Tag' %>
  <%= f.text_field :bikeid, :for => "bikeid", :placeholder => "\"A1000\"", error: 'Test stuff' %>
</section>
  
<section class="formElem">
  <%= f.label :serialnumber, 'Serial Number' %>
  <%= f.number_field :serialnumber, :step => "1", :placeholder => "\"12345\"", min:1 %>
</section>
  
<section class="formElem">
  <%= f.label :rating, 'User Rating' %>
  <%= f.select :rating, ['Poor', 'Average', 'Good'] %>
</section>

<section class="formElem">
  <%= f.label :condition, 'Current Condition' %>
  <%= f.select :condition, ['Poor', 'Good', 'Excellent'] %>
</section>
  
<section class="formElem">
  <%= f.label :maintenance, 'Last Maintenance' %>
  <%= f.date_field :maintenance, max: Date.today %>
</section>
  
<section class="formElem">
  <%= f.label :style, 'Style (Type)' %>
  <%= f.select :style, ['Mountain', 'Road', 'Touring'] %>
</section>

<section class="formElem">
  <%= f.label :size, 'Size (cm)' %>
  <%= f.number_field :size,min: 30, :placeholder => "\"64\"" %>
</section>

<section class="formElem">
  <%= f.label :color, 'Primary Color' %>
  <%= f.select :color, ['Red', 'Orange', 'Yellow', 'Green', 'Cyan', 'Blue', 'Purple', 'Violet', 'Pink', 'Magenta', 'White', 'Gray', 'Black', 'Brown'] %>
</section>
  
<section class="formElem">
  <%= f.label :availability, 'Availability' %>
  <%= f.select :availability, [['Available', true], ['Not Available', false]] %>
</section>

<section class="formElem">
  <%= f.label :lastcheck, 'Last Check-in' %>
  <%= f.date_field :lastcheck, max: Date.today %>
</section>

<section class="formElem">
  <%= f.label :location, 'Current Location' %>
  <%= f.text_field :location, :placeholder => "\"Stanley Thomas\"", minlength: 4 %>
</section>

<section class="formElem">
  <%= f.label :fare, 'Fare ($)' %>
  <%= f.number_field :fare, :step => '0.01',min: 1, :placeholder => "\"2.50\"" %>
</section>

<section class="formElem">
  <%= f.label :accessories, 'Accessories' %>
  <%= f.text_field :accessories, :placeholder => "\"None\"" %>
</section>

<section class="formElem">
  <%= f.label :picture, 'Picture' %>
  <!--For uploading a file<td>%= f.file_field :picture, accept: 'image/png,image/gif,image/jpeg' %></td>-->
  <%= f.text_field :picture, :placeholder => "\"https://example.com/bike.png\"", minlength: 13 %>
</section>

app/views/bikes/_bike_nav.html.erb
<nav class="miniNav uk-text-center">
	
	<!--Show back if not on bike index-->
	<% unless current_page?("/bikes") %>
		<%= link_to 'Return to Bikes', bikes_path, class: "uk-button uk-button-default" %>
	<% end %>
	
	<% if isAdmin() %>
		<!--Show add/edit if on index/show respectively-->
		<% if current_page?("/bikes") %>
			<%= link_to 'Add new bike', new_bike_path, class: "uk-button uk-button-default" %>
		<% elsif params[:action] == "show" %>
			<%= link_to 'Edit this bike', edit_bike_path(@bike), class: "uk-button uk-button-primary" %>
		<% end %>
	<% end %>
	
</nav>

app/views/bikes/_bike_show.html.erb
<h1 class="stretch-none uk-text-center">Bike <%= @bike.bikeid %></h1>


<% t = @bike %>

<div class="stretch uk-child-width-1-1" uk-grid>
  
  <section>
    
    <img src="<%= t.picture %>" alt="<%= t.color %> <%= t.style %> Bike" width='400'>

		<p>Fare: $<%= number_with_precision(t.fare, :precision => 2) %> + $<%= number_with_precision(t.fare*0.10, :precision => 2) %> per hour</p>
    <p>Description: <span class="uk-text-capitalize"><%= t.size %>cm</span> <span class="uk-text-capitalize"><%= t.color %></span> <span class="uk-text-capitalize"><%= t.style %></span> Bike
    <% if (t.accessories != "None") %>
      with <%= t.accessories %>
    <% end %> in <span class="uk-text-capitalize"><%= t.rating %></span> condition.
    </p>
    
		<p>Last Maintenance: <%= t.maintenance.strftime("%m/%d/%Y") %></p>
		
		<% if t.availability %>
			<p>Available &ndash; Current Location: <%= t.location %></p>
			<a href="<%= bikes_path %>/<%= t.id %>/switchAvailability" data-confirm="Are you sure you want to check out this bike? It will cost $<%= number_with_precision(t.fare, :precision => 2) %> + $<%= number_with_precision(t.fare*0.10, :precision => 2) %> / hour" class="uk-button uk-button-primary uk-width-1-1">Check Out</a>
		<% else %>
			<p>Checked-Out &mdash; Last Checked-in: <%= t.lastcheck %></p>
			<a href="<%= bikes_path %>/<%= t.id %>/switchAvailability" class="uk-button uk-button-primary uk-width-1-1">Check In</a>
		<% end %>
    
    
    
  </section>
  
</div>

app/views/bikes/edit.html.erb
<% @pageName = "Bikes" %>
<% @pageSection = "Edit" %>

<%= render :partial => 'bike_nav' %>

<h2>Edit a Bike</h2>

<%= form_for @bike do |f| %>

  <%= render :partial => 'bike_form', :locals => {:f => f} %>
  
  <section class="formElem" id="submitSect">
    <%= button_to "Update Bike", bike_path(@bike), :method => :create, :class => "boot", :id => "create" %>
    <%= link_to "Delete Bike", bike_path(@bike), :method => :delete, :class => "boot", :id => "delete", :data => { confirm: "Are you sure you want to delete Bike #{@bike.bikeid}?" } %>
  </section>

<% end %>

app/views/bikes/index.html.erb
<% @pageName = "Bikes" %>
<% @pageSection = "All" %>

<h1 class="stretch-none uk-text-center">Bike Inventory</h1>

<%= render :partial => '/renters/renter_tickets', :locals => {:tickets => @tickets} %>


<%= render :partial => 'bike_nav' %>

<h2 style="text-align: center">All Bikes</h2>
<!--Displays table listing attributes for all bikes-->
<div class="uk-margin-bottom">
	<div class="dataDisp uk-margin-bottom">
		
		<% @bikes.each do |t| %>
			<a href="<%= bikes_path %>/<%= t.id %>" class="uk-card uk-card-hover dataBlock uk-padding uk-text-uppercase">
				
					<div class="uk-card-body uk-grid-collpase uk-child-width-3-1 uk-text-center uk-padding-none" uk-grid>
						
						<!--Bike Image-->
						<div class="uk-card-media-left dataPicMargin">
							<img class="uk-border-rounded dataPic" style="background-image: url('<%= t.picture %>');" alt="<%= t.color %> <%= t.style %> Bike" src="<%= t.picture %>">
						</div>
						
						<!--Bike Status-->
						<div class="status uk-border-rounded
						<% if t.availability %>
							available
						<% else %>
							unavailable
						<% end %>"></div>
						
						<!--Bike Content-->
						<div class="dataContent">
							<% if t.availability %>
								<p>Fare: $<%= number_with_precision(t.fare, :precision => 2) %> + $<%= number_with_precision(t.fare*0.10, :precision => 2) %> / hour</p>
								<p>Rating: <%= t.rating %></p>
								<p><%= t.location %></p>
							<% else %>
								<p>Checked-Out</p>
							<% end %>
						</div>
						
					</div>
					
			</a>
		<% end %>
		
	</div>
	
	<!-- Adds pagination/navigation from Kaminari -->
	<div style="text-align: center;">
		<%= paginate @bikes, :param_name => "bike_page" %>
		<div style="clear: both;">
			<%= page_entries_info @bikes %>
		</div> 
	</div>

</div>

app/views/bikes/new.html.erb
<% @pageName = "Bikes" %>
<% @pageSection = "New" %>

<%= render :partial => 'bike_nav' %>

<h2>Add a Bike</h2>

<%= simple_form_for @bike do |f| %>

  <%= render :partial => 'bike_form', :locals => {:f => f} %>
  
  <section class="formElem">
    <%= f.button :submit %>
  </section>

<% end %>

app/views/bikes/show.html.erb
<% @pageName = "Bike #{@bike.bikeid}" %>

<%= render :partial => 'bike_nav' %>

<%= render :partial => 'bike_show' %>

app/views/bikes/switchAvailability.html.erb
<%= render :partial => 'bike_nav' %>

#<%= puts flash[:newAvailability] %>
<h1>The bike's availability is now <%= @newAvailability %>.</h1>
<p>Click <a href="<%= bikes_path %>/<%= @bike.id %>">here</a> to return to previous page.</p>