config/routes.rb
Rails.application.routes.draw do

  get 'payments/index'

  get 'payments/new'

  get 'payments/create'

    #get 'sessions/create'
    
    #get 'sessions/destroy'
    
    get 'home/show'

    get '/bikes/:id/switchAvailability', to: 'bikes#switchAvailability'
    get '/bikes/new', to: 'bikes#new'
    get '/bikes/:id/edit', to: 'bikes#edit'
    get '/bikes/:id/checkin', to: 'bikes#checkin'
    
    get '/about', to: 'home#about'
    get '/pricing', to: 'home#pricing'
    get '/error', to: 'home#error'
    
    #Creates standard routes for different controllers
    resources :bikes
    resources :renters
    resources :tickets
    
    #Makes home page bikes#index view
    #root :to => redirect('/bikes')
    

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    
    # Added these for cucumber testing
    # sessions#create_guest makes a fake user for Cucumber testing with hard coded data 
    # so that session[:logged_in] is true
    get 'auth/guest', to: 'sessions#create_guest'
    # sessions#loggedin checks that the user is logged in and outputs session[:logged_in] to log folder
    # Since it is used by Cucumber, the output is put into the bottom of log/test.log
    get 'auth/loggedin', to: 'sessions#loggedin'

    resources :sessions, only: [:create, :destroy]
    get '/login', to: 'sessions#login'
    
    resource :home, only: [:show]

    root to: "home#show"
    
    resources :payments, only: [:index, :new, :create]
    
    get '*path' => redirect('/error')
    
    
end

app/models/payment.rb
#Model for processing payments
class Payment < ActiveRecord::Base
  require "active_merchant/billing/rails"

  attr_accessor :card_security_code
  attr_accessor :credit_card_number
  attr_accessor :expiration_month
  attr_accessor :expiration_year

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :card_security_code, presence: true
  validates :credit_card_number, presence: true
  validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :expiration_year, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  validate :valid_card

  #Creates credit card object to be used for payment
  def credit_card
    ActiveMerchant::Billing::CreditCard.new(
      number:              credit_card_number,
      verification_value:  card_security_code,
      month:               expiration_month,
      year:                expiration_year,
      first_name:          first_name,
      last_name:           last_name
    )
  end

  #Checks to see if credit card is valid
  def valid_card
    if !credit_card.valid?
      errors.add(:base, "The credit card information you provided is not valid.  Please double check the information you provided and then try again.")
      false
    else
      true
    end
  end

  #Checks validity of credit card and charges the given payment amount to the card
  def process
    if valid_card
      response = GATEWAY.authorize(amount * 100, credit_card)
      if response.success?
        transaction = GATEWAY.capture(amount * 100, response.authorization)
        if !transaction.success?
          errors.add(:base, `#{credit_card.errors.full_messages.join('. ')}`) and return
          false
        end
        update_columns({authorization_code: transaction.authorization, success: true})
        true
      else
        errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
        false
      end
    end
  end
end

app/controllers/payments_controller.rb
#Controller for processing payments
class PaymentsController < ApplicationController
  
  #Filters for payment page 
  before_action :force_log_in
  before_action :require_admin, except: [:new, :create]

  #Shows all current payments
  def index
    @payments = Payment.all
  end

  #Default CRUD
  def new
    @payment = Payment.new
  end

  #Default CRUD
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      if @payment.process
        # redirect_to payments_path, notice: "The user has been successfully charged." and return
        session[:paid] = true
        redirect_to :controller => 'bikes', :action => 'checkin', :id => session[:bikeid] and return
      end
    end
    render 'new'
  end

  private
    #Used for CRUD
    #Requires first_name, last_name, credit_card_number, expiration_month, expiration_year, card_security_code, amount
    def payment_params
      params.require(:payment).permit(:first_name, :last_name, :credit_card_number, :expiration_month, :expiration_year, :card_security_code, :amount)
    end
 
end

app/helpers/payments_helper.rb
#Helps the payment process
module PaymentsHelper
  
  #Generates dictionary of months
  def months
    (1..12).collect{|n| ["#{n} - #{Date::MONTHNAMES[n]}", n]}
  end

  #Generates list of years from now to 15 years in the future
  def years
    (Time.now.year..Time.now.year+15)
  end
end

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/index.html.erb
<h1>Payment Attempts</h1>
<div class="well">
<%= link_to "New Payment", new_payment_path, class: "btn btn-primary" %>
</div>
<% if !flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-bordered table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Last 4</th>
    <th>Amount</th>
    <th>Succeeded?</th>
    <th>Authorization Code</th>
  </tr>
  <% if @payments.size > 0 %>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.first_name %></td>
        <td><%= payment.last_name %></td>
        <td><%= payment.last4 %></td>
        <td><%= number_to_currency payment.amount %></td>
        <td><%= payment.success == true ? "Yes" : "No" %></td>
        <td><%= payment.authorization_code %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="5">No payments have been attempted.</td>
    </tr>
  <% end %>
</table>

app/views/payments/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>New Payment</h1>
    <p>Test Credit Cards: 4111111111111111, 4012888888881881</p>
    <% if @payment.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @payment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="well">
      <%= simple_form_for @payment do |f| %>
        <div class="form-group">
          <%= f.label :first_name, class: "control-label" %>
          <%= f.text_field :first_name, maxlength: 32, size: 32, class: "form-control", :value => current_user.renterName.split(" ")[0] %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, class: "control-label" %>
          <%= f.text_field :last_name, maxlength: 32, size:32, class: "form-control", :value => current_user.renterName.split(" ")[1] %>
        </div>
        <div class="form-group">
          <%= f.label :credit_card_number, class: "control-label" %>
          <%= f.text_field :credit_card_number, minlength: 16, maxlength: 16,size: 16, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_month, class: "control-label" %>
          <%= f.select :expiration_month, months, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_year, class: "control-label" %>
          <%= f.select :expiration_year, years, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :card_security_code, class: "control-label" %>
          <%= f.text_field :card_security_code, minlength: 3, maxlength: 3,size: 3, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :amount, label: "Amount ($)", class: "control-label" %>
          <%= f.number_field :amount, precision: 2, class: "form-control",:value => number_with_precision(session[:amount], precision: 2), step: "0.01", :readonly => true %>
        </div>
        <div class="form-group">
          <%= f.submit "Charge Credit Card", class: "btn btn-primary uk-button uk-button-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>